# This is music in motion
echo "Sucker for Pain"
echo "Runaway"
echo "Chemically Imbalanced"
echo "God Love Her"
echo "I Saw God Today"
echo "Grace"
echo "Falling Apart"
echo "Watching Airplanes"
echo "Drinkin' Problem"
echo "How to Save a Life(New Version)"
echo "Whiskey Glasses"
echo "Great Vacation"
echo "Under My Skin"
echo "The Devil Is a Lie (feat. JAY-Z)E"
echo "WHARF TALK (feat. A$AP Rocky)E"
echo "REDMERCEDES E"
echo "pride.is.the.devil E"
echo "Stereo Heart (feat. Adam Levine)"
echo "Paralyzed"
echo "Icon E"
echo "Eternity (feat. John Legend)"
echo "Someone You Loved"
echo "Sunflower E"
echo "Something in teh Way She Moves"
echo "I Won't Give Up"
echo "Turtles All the Way Down"
echo "Electricty Is in My Soul"
echo "Loving You"
echo "Linger"
echo "Start Again"
echo "Back To Back"
